export const initReg = {  
  Name: '',        
  EncCompanyId: '',
  PartyCode: 0,
  PartyId: 0,
  UserId: 0,
  RegMob1: '',
  Email: '', 
  Address: '',
  UserPassword: '',
  UserType: '',
  Address2: '',
  City: '',
  State: 3,
  StateName: 'West Bengal',
  Pin: '',        
  DOB: '',
  DOBstr: '',
  Age: '',
  AgeMonth: '',
  AgeDay: '',
  IsDOBCalculated: 'N',
  GenderDesc: 'Male',
  Gender: 104,
  Country: 1,
  MemberId: '',

  Aadhaar: "",
  Salutation: "",
  Qualification: "",
  SpecialistId: 0,
  AnniversaryDate: "",
  AnniversaryDatestr: "",
  compName: "",
  compAddress: "",
  compState: "",
  compPin: "",
  compPhone1: "",
  compPhone2: "",
  compMail: "",

  BusinessType: '',
  ContactPerson: '',  // for Business type.
  RegMob2: '',               
  GstIn: '',
  LicenceNo: '',
  DL_Number2: '',
  TradeLicense: '',

  UserRegTypeId: '',
}

export const initMember = {
  Salutation: '',
  MemberName : '',
  EncCompanyId: '',    
  RegMob1: '',
  Gender: '',
  GenderDesc: '',
  Address: '',
  Age: '0',
  AgeMonth: '0',
  AgeDay: '0',           
  State: '3',
  City: '',
  Pin: '',
  Landmark: '',
  ParentUserId: 0,
  MemberId: 0,
  MemberTypeId : 0,
  UserType: '',
  UID: '',
  UserId: '',
  DOB: '',
  DOBstr: '',
  IsDOBCalculated: 'N',
  Aadhaar: '',
  ParentAadhaar1: '',
  ParentAadhaar2: '',
  RelationShipWithHolder: '',
  Mobile: '',
  Country: 1,
  Mobile2: '',
  GstIn: '',
  LicenceNo: '',
  ContactPerson: '',
  BusinessType: '',
  // UserRegTypeId: ''
  PartyId: '',
  LinkAutoId: 0,          // when doctor add member of other user.
}

export const BASE_URL = 'https://myapps.gsterpsoft.com'
export const GSTERPSOFT_URL = 'https://apigst.gsterpsoft.com'  
export const SRC_URL = 'https://erp.gsterpsoft.com';