import colors from 'tailwindcss/colors.js';
export const zero = 'tSL0lTwETc1vrrU2ZIoFFA==';
export const defaultId = 'FFCeIi27FQMTNGpatwiktw==';  
export const initReg = {  
  Name: '',        
  EncCompanyId: '',
  PartyCode: 0,
  PartyId: 0,
  UserId: 0,
  RegMob1: '',
  Email: '', 
  Address: '',
  UserPassword: '',
  UserType: '',
  Address2: '',
  City: '',
  State: 3,
  StateName: 'West Bengal',
  Pin: '',        
  DOB: '',
  DOBstr: '',
  Age: '',
  AgeMonth: '',
  AgeDay: '',
  IsDOBCalculated: 'N',
  GenderDesc: 'Male',
  Gender: 104,
  Country: 1,
  MemberId: '',

  Aadhaar: "",
  Salutation: "",
  Qualification: "",
  SpecialistId: 0,
  AnniversaryDate: "",
  AnniversaryDatestr: "",
  compName: "",
  compAddress: "",
  compState: "",
  compPin: "",
  compPhone1: "",
  compPhone2: "",
  compMail: "",

  BusinessType: '',
  ContactPerson: '',  // for Business type.
  RegMob2: '',               
  GstIn: '',
  LicenceNo: '',
  DL_Number2: '',
  TradeLicense: '',

  UserRegTypeId: '',
}

export const initMember = {
  Salutation: '',
  MemberName : '',
  EncCompanyId: '',    
  RegMob1: '',
  Gender: '',
  GenderDesc: '',
  Address: '',
  Age: '0',
  AgeMonth: '0',
  AgeDay: '0',           
  State: '3',
  City: '',
  Pin: '',
  Landmark: '',
  ParentUserId: 0,
  MemberId: 0,
  MemberTypeId : 0,
  UserType: '',
  UID: '',
  UserId: '',
  DOB: '',
  DOBstr: '',
  IsDOBCalculated: 'N',
  Aadhaar: '',
  ParentAadhaar1: '',
  ParentAadhaar2: '',
  RelationShipWithHolder: '',
  Mobile: '',
  Country: 1,
  Mobile2: '',
  GstIn: '',
  LicenceNo: '',
  ContactPerson: '',
  BusinessType: '',
  // UserRegTypeId: ''
  PartyId: '',
  LinkAutoId: 0,          // when doctor add member of other user.
}

export const BASE_URL = 'https://myapps.gsterpsoft.com'
export const GSTERPSOFT_URL = 'https://apigst.gsterpsoft.com'  
export const SRC_URL = 'https://erp.gsterpsoft.com';

export const dummyUser = {
  "UserId": 14701,
  "UserName": null,
  "UserPassword": "1234",
  "UserFullName": "Sujeet Kr. Ram",
  "Email": "",
  "MobileNo": "6000000010",
  "Salutation": "",
  "Name": "Sujeet Kr. Ram",
  "Address": "some random address",
  "Address2": "",
  "Address3": "",
  "Address4": "",
  "City": "Maheshtala",
  "Pin": "700120",
  "RegMob1": "6000000010",
  "RegMob2": "",
  "MobOTP": "",
  "UserType": "PATIENT",
  "Age": 1,
  "AgeMonth": 11,
  "AgeDay": 13,
  "Gender": 104,
  "GenderDesc": "Male",
  "PartyCode": 1249964,
  "PartyId": 1196709,
  "MemberId": 677,
  "MPartyCode": "100647",
  "Qualification": "",
  "SpecialistId": 0,
  "SpecialistDesc": "",
  "RegNo": "",
  "Country": 1,
  "State": 3,
  "StateName": "West Bengal",
  "DOB": "2023-02-21T00:00:00",
  "DOBstr": null,
  "AnniversaryDate": "0001-01-01T00:00:00",
  "Aadhaar": "",
  "IsDOBCalculated": null,
  "DeptId": 0,
  "PartyTypeDesc": "Customer",
  "Accode": 0,
  "GstIn": "",
  "DL_Number": null,
  "DL_Number2": null,
  "TradeLicense": null,
  "LicenceNo": "",
  "ContactPerson": "",
  "BusinessType": "",
  "UserRegTypeId": 43198,
  "UserRegTypeValue": "Customer",
  "UserRegTypeDesc": "Customer",
  "IsActive": "Y",
  "ParentUserId": 0,
  "UserMemberAutoId": 0,
  "IDCardTypeId": 0,
  "IDCardTypeDesc": null,
  "IDCardTypeNo": null,
  "OpportunityId": 0,
  "ItemId": 0,
  "Description": null,
  "Amount": 0,
  "BillId": 0,
  "PBankId": 0,
  "UserRoleId": 17908,
  "UserRoleLevelName": "User-Dept",
  "UserRoleLevelCode": "54",
  "EmpId": "0",
  "UserAccess": 1,
  "UserLevelSeq": 54,
  "UnderDoctId": 0,
  "UnderDoctDesc": null,
  "ReferrerId": 0,
  "ReferrerDesc": null,
  "ProviderId": 0,
  "ProviderDesc": null,
  "MarketedId": 0,
  "MarketedDesc": null,
  "UserTypeId": 0,
  "RollId": 0,
  "RollDesc": null,
  "NextAppDate": "0001-01-01T00:00:00",
  "NextAppDateStr": null,
  "UserAccessList": null,
  "EnclosedDocObj": null,
  "UserMemberLink": null,
  "UserCompList": null,
  "InsDate": "0001-01-01T00:00:00",
  "InsBy": 0,
  "ModiDate": "0001-01-01T00:00:00",
  "ModiBy": 0,
  "Modistatus": null,
  "DelDate": "0001-01-01T00:00:00",
  "DelBy": 0,
  "Delstatus": null,
  "CompanyId": 0,
  "EncCompanyId": "FFCeIi27FQMTNGpatwiktw==",
  "CompanyName": null,
  "CompUserPartyCode": 0,
  "CompUserMPartyCode": null,
  "LocationId": 0,
  "FinYear": 0,
  "Remarks": "",
  "RegMode": null,
  "LocationName": null,
  "ExchangeRate": 0,
  "INREquivalent": 0,
  "ForexSign": null,
  "ROUNDOFFHEAD": 0,
  "ROUNDOFF": 0,
  "RoundOffType": null,
  "TermsAndConditions": null,
  "BankDetails": null,
  "CGSTTAXTYPE": 0,
  "SGSTTAXTYPE": 0,
  "IGSTTAXTYPE": 0,
  "CESSTAXTYPE": 0,
  "UTGSTTAXTYPE": 0,
  "IsGST": null,
  "SGSTPACHEAD": 0,
  "CGSTPACHEAD": 0,
  "IGSTPACHEAD": 0,
  "UTGSTPACHEAD": 0,
  "SGSTSUSPACHEAD": 0,
  "CGSTSUSPACHEAD": 0,
  "IGSTSUSPACHEAD": 0,
  "UTGSTSUSPACHEAD": 0,
  "SGSTADVACHEAD": 0,
  "CGSTADVACHEAD": 0,
  "IGSTADVACHEAD": 0,
  "UTGSTADVACHEAD": 0,
  "CESSADVACHEAD": 0,
  "CESSRACHEAD": 0,
  "CESSPACHEAD": 0,
  "CESSRSUSACHEAD": 0,
  "CGST": 0,
  "SGST": 0,
  "IGST": 0,
  "UTGST": 0,
  "CESS": 0,
  "CCESS": 0,
  "ICESS": 0,
  "TotalTax": 0,
  "MRPValue": 0,
  "Savings": 0,
  "SavingsPer": 0,
  "RateCondition": null,
  "ConditionalAmt": 0,
  "CGSTRATE": 0,
  "SGSTRATE": 0,
  "IGSTRATE": 0,
  "OLDCGSTRATE": 0,
  "OLDSGSTRATE": 0,
  "OLDIGSTRATE": 0,
  "ConditionalCGSTRATE": 0,
  "ConditionalSGSTRATE": 0,
  "ConditionalIGSTRATE": 0,
  "UTGSTRATE": 0,
  "CESSRATE": 0,
  "SGSTRACHEAD": 0,
  "CGSTRACHEAD": 0,
  "IGSTRACHEAD": 0,
  "UTGSTRACHEAD": 0,
  "StockInOutQty": 0,
  "VisitNo": null,
  "IsProvisionalInv": null,
  "EC_GSTIN": null,
  "IsReverseCharge": null,
  "CurrencySign": null,
  "ExportUnder": null,
  "VchNoSeries": null,
  "TrackingNo2": null,
  "TrackingNo3": null,
  "TrackingNo4": null,
  "TrackingNo5": null,
  "TrackingNo6": null,
  "NetRateS": 0,
  "ServiceStartTime": null,
  "ServiceEndTime": null,
  "IsCanceled": null,
  "CFACTOR_MRP": 0,
  "PackSizeId": 0,
  "PackSizeDesc": null,
  "UHID": "UID0000221",
  "ApprovalStatus": null,
  "BillStatus": null,
  "OrderStatus": null,
  "strManufacturingDate": null,
  "ManufacturingDate": "0001-01-01T00:00:00",
  "ExpiryDate": "0001-01-01T00:00:00",
  "ERRORCODE": null,
  "MODCOUNTER": 0,
  "VisitId": 0,
  "VisitRefType": null,
  "PartyType": 25,
  "FinYearCode": 0,
  "BedCaption": null,
  "IsEnabled": null,
  "TranRefType": null,
  "LineItemDisc": null,
  "LoginMode": null,
  "InsByDesc": null,
  "CashLedgerId": 0,
  "BankLedgerId": 0
}


export const myColors = {
  primary: {
    50:  colors.slate[50],
    100: colors.slate[100],
    200: colors.slate[200],
    300: colors.slate[300],
    400: colors.slate[400],
    500: colors.slate[500],
    600: colors.slate[600],
    700: colors.slate[700],
    800: colors.slate[800],
    900: colors.slate[900],
  },
  bahia: {
    50: '#f9fbea',
    100: '#f0f6d1',
    200: '#e0eda9',
    300: '#c9e076',
    400: '#aecd42',
    500: '#94b52d',
    600: '#739020',
    700: '#586e1d',
    800: '#47581c',
    900: '#3c4b1c',
    950: '#1f290a',
  },
}