// import Constants from "expo-constants";
import colors from 'tailwindcss/colors.js';

// export const { compId, baseUrl, srcUrl } = Constants.expoConfig.extra || {};

export const zero = 'tSL0lTwETc1vrrU2ZIoFFA==';
export const defaultId = 'FFCeIi27FQMTNGpatwiktw=='; 
export const TAKEHOME_PHARMA = 'yFObpUjTIGhK9%2B4bFmadRg==';
export const TAKEHOME_AGRO = '5KR8RKKh%2BtHG4iszAzAjJQ==';
export const TAKEHOME_GARMENTS = 't0ZL5KiikMgM1YeyB68a1w==';
export const TAKEHOME_ELECTRONICS = 'QqFodfpxRStiGjTKTYE/hA==';
export const TAKEHOME_SURGICAL = 'aS8HN5gcPcKUC8hc/JCvBA==';
export const BC_ROY = 'ji4C/%2BQbn%2BBofLeoFG9clw=='
export const HEXAGON_ID = 'CHEZmvXXLYNYZOKVN9fr5A==';
export const rent = false;
export const blur = false;

const REACT_APP_BASE_URL = 'https://myapps.gsterpsoft.com';
const REACT_APP_TEST_BASE_URL = 'https://api.gsterpsoft.com';

export const testMode = false;

// export const BASE_URL = testMode ? REACT_APP_TEST_BASE_URL : REACT_APP_BASE_URL;
// export const SRC_URL = 'https://erp.gsterpsoft.com';

export const BASE_URL = 'https://apigst.gsterpsoft.com';
export const SRC_URL = 'https://gsterpsoft.com';

export const permissions = {
  appointments: [BC_ROY, defaultId],
  labtest: [defaultId],
  shop: [TAKEHOME_PHARMA, TAKEHOME_AGRO, TAKEHOME_ELECTRONICS, TAKEHOME_GARMENTS],
};

export const hasAccess = (module: string, role: string) => {
  return permissions[module]?.includes(role);
};

export const versions = {
  takehome: '1.0.4',
  bcroy: '1.0.2',
  gbooks: '1.0.0'
}

export const initLocation = {
  required: true, 
  LocationId: 0,
  LocationName: '', 
  Address: '', 
  StateDesc: '', 
  StateCode: 0, 
  PIN: '', 
  Area: ''
}

export const initReg = {  
  Name: '',        
  EncCompanyId: '',
  PartyCode: 0,
  PartyId: 0,
  UserId: 0,
  RegMob1: '',
  Email: '', 
  Address: '',
  UserPassword: '',
  UserType: '',
  Address2: '',
  City: '',
  State: 3,
  StateName: 'West Bengal',
  Pin: '',        
  DOB: '',
  DOBstr: '',
  Age: '',
  AgeMonth: '',
  AgeDay: '',
  IsDOBCalculated: 'N',
  GenderDesc: 'Male',
  Gender: 104,
  Country: 1,
  MemberId: '',

  Aadhaar: "",
  Salutation: "",
  Qualification: "",
  SpecialistId: 0,
  AnniversaryDate: "",
  AnniversaryDatestr: "",
  compName: "",
  compAddress: "",
  compState: "",
  compPin: "",
  compPhone1: "",
  compPhone2: "",
  compMail: "",

  BusinessType: '',
  ContactPerson: '',  // for Business type.
  RegMob2: '',               
  GstIn: '',
  LicenceNo: '',
  DL_Number2: '',
  TradeLicense: '',

  UserRegTypeId: '',
  UserLevelSeq: ''
}

export const initMember = {
  Salutation: '',
  MemberName : '',
  EncCompanyId: '',    
  RegMob1: '',
  Gender: '',
  GenderDesc: '',
  Address: '',
  Age: '0',
  AgeMonth: '0',
  AgeDay: '0',           
  State: '3',
  City: '',
  Pin: '',
  Landmark: '',
  ParentUserId: 0,
  MemberId: 0,
  MemberTypeId : 0,
  UserType: '',
  UID: '',
  UserId: '',
  DOB: '',
  DOBstr: '',
  IsDOBCalculated: 'N',
  Aadhaar: '',
  ParentAadhaar1: '',
  ParentAadhaar2: '',
  RelationShipWithHolder: '',
  Mobile: '',
  Country: 1,
  Mobile2: '',
  GstIn: '',
  LicenceNo: '',
  ContactPerson: '',
  BusinessType: '',
  // UserRegTypeId: ''
  PartyId: '',
  LinkAutoId: 0,          // when doctor add member of other user.
}

export const dummyUser = {
    "UserId": 15208,
    "UserName": null,
    "UserPassword": "1234",
    "UserFullName": "MARKET BY USER",
    "Email": "",
    "MobileNo": "6000000056",
    "Salutation": "",
    "Name": "MARKET BY USER",
    "Address": "Market By Address",
    "Address2": "",
    "Address3": "",
    "Address4": "",
    "City": "Maheshtala",
    "Pin": "123456",
    "RegMob1": "6000000056",
    "RegMob2": "",
    "MobOTP": "",
    "UserType": "MARKETBY",
    "Age": 5,
    "AgeMonth": 6,
    "AgeDay": 7,
    "Gender": 104,
    "GenderDesc": "Male",
    "PartyCode": 1689461,
    "PartyId": 1642896,
    "MemberId": 914,
    "MPartyCode": "M00019",
    "Qualification": "",
    "SpecialistId": 0,
    "SpecialistDesc": "",
    "RegNo": "",
    "Country": 1,
    "State": 3,
    "StateName": "West Bengal",
    "DOB": "2020-01-24T00:00:00",
    "DOBstr": null,
    "AnniversaryDate": "0001-01-01T00:00:00",
    "Aadhaar": "",
    "IsDOBCalculated": null,
    "DeptId": 0,
    "PartyTypeDesc": "MarketBy",
    "Accode": 0,
    "GstIn": "",
    "DL_Number": null,
    "DL_Number2": null,
    "TradeLicense": null,
    "LicenceNo": "",
    "ContactPerson": "",
    "BusinessType": "B2C",
    "UserRegTypeId": 43352,
    "UserRegTypeValue": "MarketBy",
    "UserRegTypeDesc": "Market By",
    "IsActive": "Y",
    "ParentUserId": 0,
    "UserMemberAutoId": 0,
    "IDCardTypeId": 0,
    "IDCardTypeDesc": null,
    "IDCardTypeNo": null,
    "OpportunityId": 0,
    "PrevOpportunityId": 0,
    "NextOpportunityId": 0,
    "ItemId": 0,
    "Description": null,
    "Amount": 0,
    "BillId": 0,
    "PBankId": 0,
    "PBankDesc": null,
    "UserRoleId": 17909,
    "UserRoleLevelName": "Marketing Executive",
    "UserRoleLevelCode": "55",
    "EmpId": "0",
    "UserAccess": 1,
    "UserLevelSeq": 55,
    "UnderDoctId": 0,
    "UnderDoctDesc": null,
    "ReferrerId": 0,
    "ReferrerDesc": null,
    "ProviderId": 0,
    "ProviderDesc": null,
    "MarketedId": 0,
    "MarketedDesc": null,
    "CollectorId": 0,
    "CollectorDesc": null,
    "AppointmentToId": 0,
    "AppointmentTo": null,
    "UserTypeId": 0,
    "RollId": 0,
    "RollDesc": null,
    "EnqStatusId": 0,
    "EnqStatusValue": null,
    "NextAppDate": "0001-01-01T00:00:00",
    "NextAppDateStr": null,
    "NextAppTime": null,
    "BillType": null,
    "LINKURL": null,
    "ParentId": 0,
    "RootId": 0,
    "FollowUpId": 0,
    "PrevRefType": null,
    "UserAccessList": null,
    "EnclosedDocObj": null,
    "UserMemberLink": null,
    "UserCompList":         {
            "COMPNAME": "XYZ Multispeciality Hospital",
            "ADDRESS": null,
            "CONTACT1": null,
            "MAILID": null,
            "LogoUrl": "612.png",
            "LogoUrl_R": null,
            "CATCHLINE": null,
            "CONTACT2": null,
            "CONTACTPERSON": null,
            "StateId": 0,
            "StateDesc": null,
            "CountryId": 0,
            "CountryDesc": null,
            "PinCode": null,
            "CompCodeId": 0,
            "ParentId": 0,
            "VerticalTypeId": 0,
            "CompSeq": 0,
            "BussUnitTypeId": 0,
            "PIN": null,
            "longitude": "88.3462168978232",
            "latitude": "22.523500195639794",
            "DeptId": 28409,
            "COMPWEB": null,
            "VerticleType": null,
            "DefaultCashParty": 65472,
            "GSTIN": null,
            "PahrmaDeptId": 0,
            "PartyMasterList": [],
            "UserDetails": {
                "AccSubgroupId": 0,
                "AccSubgroupType": null,
                "AccSubgroupCollection": null,
                "TType": null,
                "MemId": 0,
                "MemIds": null,
                "SubCode": 1689461,
                "DupSubCode": 0,
                "Description": "MARKET BY USER",
                "CreationDate": "0001-01-01T00:00:00",
                "GstInDate": "0001-01-01T00:00:00",
                "Parent": null,
                "ParentDesc": null,
                "Root": null,
                "Type": "L",
                "Curr_Balance": 0,
                "AccCode": null,
                "Ledger": "1",
                "Op_Balance": 0,
                "SheetName": null,
                "CellPosition": null,
                "SheduleName": null,
                "CashBank": "R",
                "EntryMode": null,
                "UsubCode": null,
                "ParentPkId": null,
                "Note": 0,
                "LedgerCategory": 0,
                "NoteNo": null,
                "SlNo": null,
                "IsBalSheetShow": null,
                "AccCreate": null,
                "AccPartyMaster": null,
                "Deduction1Ac": 0,
                "Deduction2Ac": 0,
                "Deduction3Ac": 0,
                "Deduction1Percent": 0,
                "Deduction2Percent": 0,
                "Deduction3Percent": 0,
                "BranchId": 0,
                "IsDefault": null,
                "ParentGroup": null,
                "IsPopUp": null,
                "GroupCode": null,
                "AccruedAcNo": null,
                "InterestAcNo": null,
                "OpeningAmt": 0,
                "TranAmt": 0,
                "ClosingAmt": 0,
                "AcrudGPcode": null,
                "acrudAcDesc": null,
                "IntGPcode": null,
                "intAcDesc": null,
                "TmpAutoId": 0,
                "IFSC": null,
                "BankBranchName": null,
                "RegNo": null,
                "SWIFTCODE": null,
                "LType": null,
                "GroupId": 0,
                "MemCnt": 0,
                "CostGroupId": 0,
                "VoucherAmount": 0,
                "ProvInvBillid": 0,
                "ProvVoucherAmount": 0,
                "ProvBalAmt": 0,
                "ChkInActive": null,
                "ChkoutActive": null,
                "MarketById": 0,
                "MarketByDesc": "",
                "CollectorId": 0,
                "CollectorDesc": null,
                "EnclosedDocObj": null,
                "InsDate": "0001-01-01T00:00:00",
                "InsBy": 0,
                "ModiDate": "0001-01-01T00:00:00",
                "ModiBy": 0,
                "Modistatus": null,
                "DelDate": "0001-01-01T00:00:00",
                "DelBy": 0,
                "Delstatus": null,
                "CompanyId": 0,
                "EncCompanyId": null,
                "CompanyName": null,
                "CompUserPartyCode": 0,
                "CompUserMPartyCode": "M00019",
                "LocationId": 0,
                "FinYear": 0,
                "Remarks": null,
                "RegMode": null,
                "LocationName": null,
                "ExchangeRate": 0,
                "INREquivalent": 0,
                "ForexSign": null,
                "ROUNDOFFHEAD": 0,
                "ROUNDOFF": 0,
                "RoundOffType": null,
                "TermsAndConditions": null,
                "BankDetails": null,
                "CGSTTAXTYPE": 0,
                "SGSTTAXTYPE": 0,
                "IGSTTAXTYPE": 0,
                "CESSTAXTYPE": 0,
                "UTGSTTAXTYPE": 0,
                "IsGST": null,
                "SGSTPACHEAD": 0,
                "CGSTPACHEAD": 0,
                "IGSTPACHEAD": 0,
                "UTGSTPACHEAD": 0,
                "SGSTSUSPACHEAD": 0,
                "CGSTSUSPACHEAD": 0,
                "IGSTSUSPACHEAD": 0,
                "UTGSTSUSPACHEAD": 0,
                "SGSTADVACHEAD": 0,
                "CGSTADVACHEAD": 0,
                "IGSTADVACHEAD": 0,
                "UTGSTADVACHEAD": 0,
                "CESSADVACHEAD": 0,
                "CESSRACHEAD": 0,
                "CESSPACHEAD": 0,
                "CESSRSUSACHEAD": 0,
                "CGST": 0,
                "SGST": 0,
                "IGST": 0,
                "UTGST": 0,
                "CESS": 0,
                "CCESS": 0,
                "ICESS": 0,
                "TotalTax": 0,
                "MRPValue": 0,
                "Savings": 0,
                "SavingsPer": 0,
                "RateCondition": null,
                "ConditionalAmt": 0,
                "CGSTRATE": 0,
                "SGSTRATE": 0,
                "IGSTRATE": 0,
                "OLDCGSTRATE": 0,
                "OLDSGSTRATE": 0,
                "OLDIGSTRATE": 0,
                "ConditionalCGSTRATE": 0,
                "ConditionalSGSTRATE": 0,
                "ConditionalIGSTRATE": 0,
                "UTGSTRATE": 0,
                "CESSRATE": 0,
                "SGSTRACHEAD": 0,
                "CGSTRACHEAD": 0,
                "IGSTRACHEAD": 0,
                "UTGSTRACHEAD": 0,
                "StockInOutQty": 0,
                "VisitNo": null,
                "IsProvisionalInv": null,
                "EC_GSTIN": null,
                "IsReverseCharge": null,
                "CurrencySign": null,
                "ExportUnder": null,
                "VchNoSeries": null,
                "TrackingNo2": null,
                "TrackingNo3": null,
                "TrackingNo4": null,
                "TrackingNo5": null,
                "TrackingNo6": null,
                "NetRateS": 0,
                "ServiceStartTime": null,
                "ServiceEndTime": null,
                "IsCanceled": null,
                "CFACTOR_MRP": 0,
                "PackSizeId": 0,
                "PackSizeDesc": null,
                "UHID": null,
                "ApprovalStatus": null,
                "BillStatus": null,
                "OrderStatus": null,
                "strManufacturingDate": null,
                "ManufacturingDate": "0001-01-01T00:00:00",
                "ExpiryDate": "0001-01-01T00:00:00",
                "ERRORCODE": null,
                "MODCOUNTER": 0,
                "VisitId": 0,
                "VisitRefType": null,
                "PartyType": 374,
                "FinYearCode": 0,
                "BedCaption": null,
                "IsEnabled": null,
                "TranRefType": null,
                "LineItemDisc": null,
                "LoginMode": null,
                "InsByDesc": null,
                "CashLedgerId": 0,
                "BankLedgerId": 0,
                "LocationItemId": null,
                "DoctorGroupId": 0,
                "PatientGroupId": 0,
                "MarketGroupId": 0,
                "CollectorGroupId": 0,
                "ProviderGroupId": 0,
                "UnderDoctCaption": null,
                "ReferenceByCaption": null,
                "MarketedByCaption": null
            },
            "InsDate": "0001-01-01T00:00:00",
            "InsBy": 0,
            "ModiDate": "0001-01-01T00:00:00",
            "ModiBy": 0,
            "Modistatus": null,
            "DelDate": "0001-01-01T00:00:00",
            "DelBy": 0,
            "Delstatus": null,
            "CompanyId": 612,
            "EncCompanyId": "FFCeIi27FQMTNGpatwiktw==",
            "CompanyName": null,
            "CompUserPartyCode": 0,
            "CompUserMPartyCode": null,
            "LocationId": 928,
            "FinYear": 0,
            "Remarks": null,
            "RegMode": null,
            "LocationName": "HO",
            "ExchangeRate": 0,
            "INREquivalent": 0,
            "ForexSign": null,
            "ROUNDOFFHEAD": 0,
            "ROUNDOFF": 0,
            "RoundOffType": null,
            "TermsAndConditions": null,
            "BankDetails": null,
            "CGSTTAXTYPE": 0,
            "SGSTTAXTYPE": 0,
            "IGSTTAXTYPE": 0,
            "CESSTAXTYPE": 0,
            "UTGSTTAXTYPE": 0,
            "IsGST": null,
            "SGSTPACHEAD": 0,
            "CGSTPACHEAD": 0,
            "IGSTPACHEAD": 0,
            "UTGSTPACHEAD": 0,
            "SGSTSUSPACHEAD": 0,
            "CGSTSUSPACHEAD": 0,
            "IGSTSUSPACHEAD": 0,
            "UTGSTSUSPACHEAD": 0,
            "SGSTADVACHEAD": 0,
            "CGSTADVACHEAD": 0,
            "IGSTADVACHEAD": 0,
            "UTGSTADVACHEAD": 0,
            "CESSADVACHEAD": 0,
            "CESSRACHEAD": 0,
            "CESSPACHEAD": 0,
            "CESSRSUSACHEAD": 0,
            "CGST": 0,
            "SGST": 0,
            "IGST": 0,
            "UTGST": 0,
            "CESS": 0,
            "CCESS": 0,
            "ICESS": 0,
            "TotalTax": 0,
            "MRPValue": 0,
            "Savings": 0,
            "SavingsPer": 0,
            "RateCondition": null,
            "ConditionalAmt": 0,
            "CGSTRATE": 0,
            "SGSTRATE": 0,
            "IGSTRATE": 0,
            "OLDCGSTRATE": 0,
            "OLDSGSTRATE": 0,
            "OLDIGSTRATE": 0,
            "ConditionalCGSTRATE": 0,
            "ConditionalSGSTRATE": 0,
            "ConditionalIGSTRATE": 0,
            "UTGSTRATE": 0,
            "CESSRATE": 0,
            "SGSTRACHEAD": 0,
            "CGSTRACHEAD": 0,
            "IGSTRACHEAD": 0,
            "UTGSTRACHEAD": 0,
            "StockInOutQty": 0,
            "VisitNo": null,
            "IsProvisionalInv": null,
            "EC_GSTIN": null,
            "IsReverseCharge": null,
            "CurrencySign": null,
            "ExportUnder": null,
            "VchNoSeries": null,
            "TrackingNo2": null,
            "TrackingNo3": null,
            "TrackingNo4": null,
            "TrackingNo5": null,
            "TrackingNo6": null,
            "NetRateS": 0,
            "ServiceStartTime": null,
            "ServiceEndTime": null,
            "IsCanceled": null,
            "CFACTOR_MRP": 0,
            "PackSizeId": 0,
            "PackSizeDesc": null,
            "UHID": null,
            "ApprovalStatus": null,
            "BillStatus": null,
            "OrderStatus": null,
            "strManufacturingDate": null,
            "ManufacturingDate": "0001-01-01T00:00:00",
            "ExpiryDate": "0001-01-01T00:00:00",
            "ERRORCODE": null,
            "MODCOUNTER": 0,
            "VisitId": 0,
            "VisitRefType": null,
            "PartyType": 0,
            "FinYearCode": 0,
            "BedCaption": null,
            "IsEnabled": null,
            "TranRefType": null,
            "LineItemDisc": null,
            "LoginMode": null,
            "InsByDesc": null,
            "CashLedgerId": 0,
            "BankLedgerId": 0,
            "LocationItemId": null,
            "DoctorGroupId": 65088,
            "PatientGroupId": 65089,
            "MarketGroupId": 0,
            "CollectorGroupId": 0,
            "ProviderGroupId": 0,
            "UnderDoctCaption": "Under Doct",
            "ReferenceByCaption": "Referred By",
            "MarketedByCaption": "Marketed By",
            "SlNo": 0,
            "IsDefault": null
        },
    "DirectSalesDetailsList": null,
    "InsDate": "0001-01-01T00:00:00",
    "InsBy": 0,
    "ModiDate": "0001-01-01T00:00:00",
    "ModiBy": 0,
    "Modistatus": null,
    "DelDate": "0001-01-01T00:00:00",
    "DelBy": 0,
    "Delstatus": null,
    "CompanyId": 0,
    "EncCompanyId": "FFCeIi27FQMTNGpatwiktw==",
    "CompanyName": null,
    "CompUserPartyCode": 0,
    "CompUserMPartyCode": null,
    "LocationId": 0,
    "FinYear": 0,
    "Remarks": "",
    "RegMode": null,
    "LocationName": null,
    "ExchangeRate": 0,
    "INREquivalent": 0,
    "ForexSign": null,
    "ROUNDOFFHEAD": 0,
    "ROUNDOFF": 0,
    "RoundOffType": null,
    "TermsAndConditions": null,
    "BankDetails": null,
    "CGSTTAXTYPE": 0,
    "SGSTTAXTYPE": 0,
    "IGSTTAXTYPE": 0,
    "CESSTAXTYPE": 0,
    "UTGSTTAXTYPE": 0,
    "IsGST": null,
    "SGSTPACHEAD": 0,
    "CGSTPACHEAD": 0,
    "IGSTPACHEAD": 0,
    "UTGSTPACHEAD": 0,
    "SGSTSUSPACHEAD": 0,
    "CGSTSUSPACHEAD": 0,
    "IGSTSUSPACHEAD": 0,
    "UTGSTSUSPACHEAD": 0,
    "SGSTADVACHEAD": 0,
    "CGSTADVACHEAD": 0,
    "IGSTADVACHEAD": 0,
    "UTGSTADVACHEAD": 0,
    "CESSADVACHEAD": 0,
    "CESSRACHEAD": 0,
    "CESSPACHEAD": 0,
    "CESSRSUSACHEAD": 0,
    "CGST": 0,
    "SGST": 0,
    "IGST": 0,
    "UTGST": 0,
    "CESS": 0,
    "CCESS": 0,
    "ICESS": 0,
    "TotalTax": 0,
    "MRPValue": 0,
    "Savings": 0,
    "SavingsPer": 0,
    "RateCondition": null,
    "ConditionalAmt": 0,
    "CGSTRATE": 0,
    "SGSTRATE": 0,
    "IGSTRATE": 0,
    "OLDCGSTRATE": 0,
    "OLDSGSTRATE": 0,
    "OLDIGSTRATE": 0,
    "ConditionalCGSTRATE": 0,
    "ConditionalSGSTRATE": 0,
    "ConditionalIGSTRATE": 0,
    "UTGSTRATE": 0,
    "CESSRATE": 0,
    "SGSTRACHEAD": 0,
    "CGSTRACHEAD": 0,
    "IGSTRACHEAD": 0,
    "UTGSTRACHEAD": 0,
    "StockInOutQty": 0,
    "VisitNo": null,
    "IsProvisionalInv": null,
    "EC_GSTIN": null,
    "IsReverseCharge": null,
    "CurrencySign": null,
    "ExportUnder": null,
    "VchNoSeries": null,
    "TrackingNo2": null,
    "TrackingNo3": null,
    "TrackingNo4": null,
    "TrackingNo5": null,
    "TrackingNo6": null,
    "NetRateS": 0,
    "ServiceStartTime": null,
    "ServiceEndTime": null,
    "IsCanceled": null,
    "CFACTOR_MRP": 0,
    "PackSizeId": 0,
    "PackSizeDesc": null,
    "UHID": "",
    "ApprovalStatus": null,
    "BillStatus": null,
    "OrderStatus": null,
    "strManufacturingDate": null,
    "ManufacturingDate": "0001-01-01T00:00:00",
    "ExpiryDate": "0001-01-01T00:00:00",
    "ERRORCODE": null,
    "MODCOUNTER": 0,
    "VisitId": 0,
    "VisitRefType": null,
    "PartyType": 374,
    "FinYearCode": 0,
    "BedCaption": null,
    "IsEnabled": null,
    "TranRefType": null,
    "LineItemDisc": null,
    "LoginMode": null,
    "InsByDesc": null,
    "CashLedgerId": 0,
    "BankLedgerId": 0,
    "LocationItemId": null,
    "DoctorGroupId": 0,
    "PatientGroupId": 0,
    "MarketGroupId": 0,
    "CollectorGroupId": 0,
    "ProviderGroupId": 0,
    "UnderDoctCaption": null,
    "ReferenceByCaption": null,
    "MarketedByCaption": null,
    "SlNo": 0,
    "IsDefault": null
}

export const myColors = {
  primary: {
    50:  colors.sky[50],
    100: colors.sky[100],
    200: colors.sky[200],
    300: colors.sky[300],
    400: colors.sky[400],
    500: colors.sky[500],
    600: colors.sky[600],
    700: colors.sky[700],
    800: colors.sky[800],
    900: colors.sky[900],
  },
  bahia: {
    50: '#f9fbea',
    100: '#f0f6d1',
    200: '#e0eda9',
    300: '#c9e076',
    400: '#aecd42',
    500: '#94b52d',
    600: '#739020',
    700: '#586e1d',
    800: '#47581c',
    900: '#3c4b1c',
    950: '#1f290a',
  },
}

export const gender = [
  {CodeId: 105, Description: "Female", icon: 'face-woman-outline'},
  {CodeId: 104, Description: "Male", icon: 'face-man-outline'},
  {CodeId: 106, Description: "Trans Gender", icon: 'account-question-outline'}
]

export const states = [
  {CodeId: 3, Description: "West Bengal"},
  {CodeId: 5, Description: "Andhra Pradesh"},
  {CodeId: 1442, Description: "Arunachal Pradesh"},
  {CodeId: 1443, Description: "Assam"},
  {CodeId: 1444, Description: "Bihar"},
  {CodeId: 1445, Description: "Goa"},
  {CodeId: 1446, Description: "Gujarat"},
  {CodeId: 1447, Description: "Haryana"},
  {CodeId: 1448, Description: "Himachal Pradesh"},
  {CodeId: 1449, Description: "Jammu & Kashmir"},
  {CodeId: 1450, Description: "Karnataka"},
  {CodeId: 1451, Description: "Kerala"},
  {CodeId: 1452, Description: "Madhya Pradesh"},
  {CodeId: 1453, Description: "Maharashtra"},
  {CodeId: 1454, Description: "Meghalaya"},
  {CodeId: 1455, Description: "Mizoram"},
  {CodeId: 1456, Description: "Nagaland"},
  {CodeId: 1457, Description: "Odisha"},
  {CodeId: 1458, Description: "Punjab"},
  {CodeId: 1459, Description: "Rajasthan"},
  {CodeId: 1460, Description: "Sikkim"},
  {CodeId: 1461, Description: "Tamil Nadu"},
  {CodeId: 1462, Description: "Tripura"},
  {CodeId: 1463, Description: "Uttar Pradesh"},
  {CodeId: 1464, Description: "Chhattisgarh"},
  {CodeId: 1465, Description: "Uttarakhand"},
  {CodeId: 1466, Description: "Jharkhand"},
  {CodeId: 1467, Description: "Telangana"},
  {CodeId: 1541, Description: "New Delhi"},
  {CodeId: 1542, Description: "Andaman and Nicobar Islands"},
  {CodeId: 1543, Description: "Chandigarh"},
  {CodeId: 1544, Description: "Dadra and Nagar Haveli"},
  {CodeId: 1545, Description: "Daman and Diu"},
  {CodeId: 1546, Description: "DELHI"},
  {CodeId: 1547, Description: "Lakshadweep"},
  {CodeId: 1548, Description: "Puducherry"},
  {CodeId: 1569, Description: "Manipur"},
  {CodeId: 1573, Description: "Andhra Pradesh"}
]

export const salutations = [
  {value: 'Dr', title: 'Dr'},
  {value: 'Mr', title: 'Mr'},
  {value: 'Ms', title: 'Ms'},
  {value: 'Mrs', title: 'Mrs'},
  {value: 'Miss', title: 'Miss'},
  {value: 'BabyOf', title: 'Baby Of'},
  {value: 'Master', title: 'Master'},
  {value: 'Baby', title: 'Baby'},
  {value: 'Md', title: 'Md.'},
  {value: 'Prof', title: 'Prof.'},
  {value: 'Rev', title: 'Rev.'},
  {value: 'Sk', title: 'Sk.'}
]
